services:
  # ---- DATA LAKE STORAGE ----
  minio:
    image: minio/minio:latest
    container_name: de_project_minio
    ports:
      - "9000:9000"       # API port
      - "9001:9001"       # Web Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: securepassword123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # ---- DATA WAREHOUSE ----
  postgres:
    image: postgres:15-alpine
    container_name: de_project_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: job_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  minio_data:
  postgres_data: